language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - r: release
    - r: devel
    - os: osx
    - os: osx
      osx_image: xcode7.3
      before_install: sed -i.bak 's/-isysroot /-I/g' $(R RHOME)/etc/Makeconf
